version: '3.7'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: battle
      POSTGRES_USER: battle
      POSTGRES_PASSWORD: battle
  test-watch:
    build: backend
    command: sh -c "npm run wait-db && npm run migrate up && npm run test-watch-all"
    environment:
      DATABASE_URL: postgres://battle:battle@db:5432/battle
    volumes:
      - ./backend/src:/app/src/
      - ./backend/migrations:/app/migrations/
    depends_on:
      - db
  test-ci:
    build: backend
    command: sh -c "npm run wait-db && npm run migrate up && npm run test"
    environment:
      DATABASE_URL: postgres://battle:battle@db:5432/battle
    depends_on:
      - db
