version: '3.7'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: battle
      POSTGRES_USER: battle
      POSTGRES_PASSWORD: battle
  battle:
    build: .
    command: sh -c "npm run wait-db && npm run migrate up && npm run test-watch-all"
    environment:
      DATABASE_URL: postgres://battle:battle@db:5432/battle
    volumes:
      - ./src:/app/src/
      - ./migrations:/app/migrations/
