version: '3.7'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: battle
      POSTGRES_USER: battle
      POSTGRES_PASSWORD: battle
  battle:
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://battle:battle@db:5432/battle
    volumes:
      - ./src:/app/src/
      - ./migrations:/app/migrations/
