version: '3.7'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: battle
      POSTGRES_USER: battle
      POSTGRES_PASSWORD: battle
  backend:
    build: backend
    ports:
      - 3001:3000
    environment:
      DATABASE_URL: postgres://battle:battle@db:5432/battle
    volumes:
      - ./backend/src:/app/src/
      - ./backend/migrations:/app/migrations/
